/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.com.infomedia;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class SettingsEntryPointTest {
    @Test
    public void testAppHasAGreeting() {
        SettingsEntryPoint classUnderTest = new SettingsEntryPoint();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
